language: generic

sudo: required
services: 
  - docker

before_install:
  - docker build -t dozer1234/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dozer1234/docker-react npm run test